#!/usr/bin/env node
// Regenerates sitemap.xml by walking the repo for index.html files.
//
// The /docs/ handboek is generated by scripts/export-handboek-site.mjs in the
// gezel repo, so its page list changes without anyone editing this repo by
// hand. Deriving the sitemap from the filesystem keeps it honest; a checked-in
// list would be stale the first time the handboek is re-exported.
//
// Run after re-exporting the docs:  npm run sitemap
//
// Deliberately dependency-free, matching serve.mjs.
import { readdir, stat, writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('.', import.meta.url)));
const ORIGIN = 'https://gezel.com';
const SKIP = new Set(['.git', '.github', '.gezel', 'node_modules', 'assets']);

/** Every directory containing an index.html, as a site-absolute URL path. */
async function collect(dir = root, out = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  if (entries.some((e) => e.isFile() && e.name === 'index.html')) {
    const rel = dir.slice(root.length).split(sep).filter(Boolean).join('/');
    const { mtime } = await stat(join(dir, 'index.html'));
    out.push({ path: rel ? `/${rel}/` : '/', lastmod: mtime.toISOString().slice(0, 10) });
  }
  for (const e of entries) {
    if (e.isDirectory() && !SKIP.has(e.name) && !e.name.startsWith('.')) {
      await collect(join(dir, e.name), out);
    }
  }
  return out;
}

const pages = (await collect()).sort((a, b) => a.path.localeCompare(b.path));

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...pages.map(
    (p) => `  <url>\n    <loc>${ORIGIN}${p.path}</loc>\n    <lastmod>${p.lastmod}</lastmod>\n  </url>`,
  ),
  '</urlset>',
  '',
].join('\n');

await writeFile(join(root, 'sitemap.xml'), xml);
console.log(`sitemap.xml → ${pages.length} URLs`);
